### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by vactum0** [Ranginang67/DarkFly-Tool#10]
I don't know why I'm getting this error "exec format error"
![72216662_1346063185553140_6935882238940676096_n](https://user-images.githubusercontent.com/29106305/66306312-c2e94600-e91a-11e9-859a-1497644d8918.jpg)

**Comment by vactum0** [comment]
It's not this package's fault,
somehow we can't run exec in fish,
just run any exec directly :)

**Comment by raunakkumarsingh** [comment]
After removing previous file follow these step

Termux:

   - pkg install python2
   - pkg install git
   - git clone https://github.com/Ranginang67/DarkFly-Tool
   - cd DarkFly-Tool
   - python2 install.py

1.if installed is complite, use command
$cd
2.then run it
$DarkFly

NOTE:

if python2 install.py is not allowed or fail, Use this
$chmod +x install.py
$python2 install.py
