### ISSUE TITLE
How to Uninstall DarkFly from termux

### ISSUE THREAD

**Issue by Wjsfj51najdk** [Ranginang67/DarkFly-Tool#6]

**Comment by vactum0** [comment]
@Wjsfj51najdk did u get the answer?
I wanna know that how to install any thing like darkfly, from termux

**Comment by Gangfire** [comment]
You need to write in thermux gitclone and a link ending in .git

пн, 7 окт. 2019 г., 23:50 vactum0 <notifications@github.com>:

**Comment by vactum0** [comment]
@Gangfire  I'm really sorry, I was asking for "Uninstall" but mistakenly wrote "Install"!

**Comment by raunakkumarsingh** [comment]
follow these steps

 Termux:

   - pkg install python2
   - pkg install git
   - git clone https://github.com/Ranginang67/DarkFly-Tool
   - cd DarkFly-Tool
   - python2 install.py

1.if installed is complite, use command
$cd
2.then run it
$DarkFly

NOTE:

if python2 install.py is not allowed or fail, Use this
$chmod +x install.py
$python2 install.py

how to update:

**Comment by blackobra** [comment]
How can i use dark fly tools like information gathering
